"""add address

Revision ID: 065deb947ac2
Revises: b5cc93fa8019
Create Date: 2022-03-07 22:49:16.652851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065deb947ac2'
down_revision = 'b5cc93fa8019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
