"""user-edit

Revision ID: 8b36a7e5db3d
Revises: 065deb947ac2
Create Date: 2022-03-09 11:44:06.210572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b36a7e5db3d'
down_revision = '065deb947ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
